version: '3'

services:
  plex:
    container_name: plex-zurg
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - PLEX_UID=1001
      - PLEX_GID=1001
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-5UVDWVsQVxDhFaPtoLoz
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410
      - 32412-32414:32412-32414
      - 32469:32469
    volumes:
      - ./configs/plex/config:/config
      - ./configs/plex/transcode:/transcode
